-- AlterTable
ALTER TABLE "voice_models" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "slug" SET DATA TYPE TEXT,
ALTER COLUMN "edge_friendly_name" SET DATA TYPE TEXT,
ALTER COLUMN "edge_gender" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "edge_locale" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "edge_voice_name" SET DATA TYPE VARCHAR(255);
